<?php

/**
 * @file
 * Creates an Export View and an Import Feed for your entities
 */

/* There is a 'base' configuration. This one contains things like 'CSV', ';', etc.
Per entity-bundle we create a feed importer and a views-exporter.
We use fields and properties attached to an entity-bundle.

Baseline:
 1. a function that returns fields and properties for an entity-bundle, or all entity-bundles
 2. a function that creates a feed-configuration (specificly mapping) from a bundle-field-configuration
 3. a function that creates a view-configuration from a bundle-field-configuration

 4. a function that calls (1) an 'renders' the views and feeds
 5. a config-ui (on a central place) that calls 4 (default all enabled)
 6. a splitted config-ui (on entity settings page) that calls 4

 7. entity 'crud' listeners
 8. call 4 on install
 */


module_load_include('inc', 'mirrors', 'mirrors.defaults');
module_load_include('inc', 'mirrors', 'mirrors.feeds');
module_load_include('inc', 'mirrors', 'mirrors.views');

/**
 * Implements hook_permission().
 */
function mirrors_permission() {
  return array(
    'Administer mirrors' => array(
      'title' => t('Administer mirrors'),
      'description' => t('Use mirrors export-views.'),
    ),
  );
}

/**
 * Returns bundle configuration for supported entity and field types
 * These configurations are used by mirrors_views and mirrors_feeds
 * to create exporters and importers
 */
function mirrors_bundles() {
  $bundles = _mirrors_supported_bundles();
  $bundles = _mirrors_add_property_settings($bundles);
  $bundles = _mirrors_add_fields($bundles);

  return $bundles;
}


/**
 * Returns supported entity_types, hookable.
 */
function mirrors_entity_types() {

  $entity_types = mirrors_entity_types_defaults();
  drupal_alter('entity_types', $entity_types);

  return $entity_types;
}

/**
 * Returns supported field_types, hookable.
 */
function mirrors_field_types() {

  $field_types = mirrors_field_types_defaults();
  drupal_alter('field_types', $field_types);

  return $field_types;
}

/**
 * Returns supported field_types, hookable.
 */
function mirrors_property_types() {

  $property_types = mirrors_property_types_defaults();
  drupal_alter('property_types', $property_types);

  return $property_types;
}

/**
 * Returns a simple array with active bundles per entity_type.
 */
function _mirrors_supported_bundles() {
  $mirrors_bundles = array();

  // $bundles contains all bundles in the drupal instance
  $bundles = field_info_bundles();
  // $mirrors_entity_types contains only supported entity types
  $mirrors_entity_types = mirrors_entity_types();

  foreach ($bundles as $entity_type => $bundle) {
    if (array_key_exists($entity_type, $mirrors_entity_types)) {
      foreach ($bundle as $entity_id => $entity) {
        $mirrors_bundles[$entity_type][$entity_id] = $mirrors_entity_types[$entity_type];
      }
    }
    else {
      // Unsupported entity_type
    }
  }

  return $mirrors_bundles;
}

/**
 * Add properties settings.
 */
function _mirrors_add_property_settings($bundles) {
  $mirrors_property_types = mirrors_property_types();

  foreach ($bundles as $entity_type => &$bundle) {
    foreach ($bundle as $entity_id => &$entity) {
      foreach ($entity['properties'] as &$property) {
        // @2do: formatters for properties can be different then field formatters
        // Maybe make a seperate folder with property.inc files
        if (array_key_exists($property['type'], $mirrors_property_types)) {
          $property =  array_merge_recursive(
            $property,
            $mirrors_property_types[$property['type']]
          );
        }
      }
    }
  }

  return $bundles;
}

/**
 * Add fields to bundles.
 */
function _mirrors_add_fields($bundles) {
  $mirrors_field_types = mirrors_field_types();

  $entities = entity_get_property_info();

  // loop all, test for fields, if yes add field mapping
  foreach ($bundles as $entity_type => &$bundle) {
    foreach ($bundle as $entity_id => &$entity) {

      // FIELDS
      $mirrors_fields = array();
      // Test if bundle contains fields
      if (isset( $entities[$entity_type]['bundles'][$entity_id]['properties'] )) {
        $fields = $entities[$entity_type]['bundles'][$entity_id]['properties'];

        foreach ($fields as $key => $field) {
          $field_type = mirrors_field_type_filter_list($field['type']);

          // Test if field_type is supported by mirrors
          if (array_key_exists($field_type, $mirrors_field_types)) {
            $field = $mirrors_field_types[$field_type];
            $field['type'] = $field_type;
            $mirrors_fields[$key] = $field;
          }
          else {
            // Unsupported field type
          }
        }
      }
      $entity['fields'] = $mirrors_fields;
    }
  }

  return $bundles;
}

/**
 * Helper function for lists.
 */
function mirrors_field_type_filter_list($field_type) {
  // Check if we are dealing with a list
  if (substr($field_type, 0, 4) == 'list') {
    $mapper['separator'] = '/';

    // Extract field_type "list<$field_type>"
    $length = strlen($field_type);
    $field_type = substr($field_type, 5, $length - 6);
  }
  return $field_type;
}
