<?php

/**
 * @file
 * Mirror Profile2
 */

/**
 * Implements hook_mirrors_entity_types_alter().
 */
function mirrors_profile2_mirrors_entity_types_alter(&$mirrors_entity_types) {
  module_load_include('inc', 'mirrors_profile2', 'mirrors_profile2.defaults');

  $profile2_entity_types = mirrors_profile2_entity_types_defaults();
  $mirrors_entity_types = array_merge($mirrors_entity_types, $profile2_entity_types);
}
