<?php

/**
 * @file
 * Mirror Commerce
 */

/**
 * Implements hook_mirrors_entity_types_alter().
 */
function mirrors_commerce_mirrors_entity_types_alter(&$mirrors_entity_types) {
  module_load_include('inc', 'mirrors_commerce', 'mirrors_commerce.defaults');

  $commerce_entity_types = mirrors_commerce_entity_types_defaults();
  $mirrors_entity_types = array_merge($mirrors_entity_types, $commerce_entity_types);
}

/**
 * Implements hook_mirrors_field_types_alter().
 */
function mirrors_commerce_mirrors_field_types_alter(&$mirrors_field_types) {
  $commerce_field_types = mirrors_commerce_field_types_defaults();
  $mirrors_field_types = array_merge($mirrors_field_types, $commerce_field_types);
}
